baseURL = "https://blog.preston.io/"
languageCode = "en-us"
title = "preston.io"
theme = "alpaca"
summaryLength = 70
disqusShortname = "blog-preston-io"
[params]
  author = "Preston Pham"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true